FROM golang:1.25 AS builder
WORKDIR /build
COPY go.mod go.sum ./
RUN go mod download
COPY main.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -o webhook .

FROM gcr.io/distroless/static:nonroot
COPY --from=builder /build/webhook /webhook
USER 65534:65534
ENTRYPOINT ["/webhook"]
